name: Tauri Desktop Build

on:
  push:
    branches:
      - main
      - feature/tauri-integration
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.target || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin
            args: --target x86_64-apple-darwin
          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin
            args: --target aarch64-apple-darwin
          # Ubuntu
          - os: ubuntu-22.04
          # Windows
          - os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install system dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target || '' }}

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npm run tauri:build -- ${{ matrix.args || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snail-todolist-${{ matrix.os }}${{ matrix.target && format('-{0}', matrix.target) || '' }}
          path: |
            src-tauri/target/${{ matrix.target && format('{0}/release', matrix.target) || 'release' }}/bundle/**/*
          if-no-files-found: warn


